# Site settings
title: Brendan's Home
email: billingb@gmail.com
description: >
  Healthy recipes that taste great!
baseurl: "/recipe-blog" # the subpath of your site, e.g. /blog/
url: "https://billingb.github.io" # the base hostname & protocol for your site
twitter_username: brendanbill
github_username:  billingb
linkedin_id: brendan-billingsley-3894bb4

# Build settings
# markdown: kramdown
